services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    hostname: qdrant
    networks: ['shared_network']
    restart: unless-stopped
    ports:
      - '6333:6333'
    environment:
      - QDRANT__TELEMETRY_DISABLED=true
      - QDRANT__SERVICE__API_KEY=${QDRANT_API_KEY}
    volumes:
      - ./data/qdrant:/qdrant/storage
networks:
  shared_network:
    name: shared_network
    driver: bridge
    external: true